baseURL: https://233yeee.com/
languageCode: en-us
timeZone: Canada/Pacific
title: Yanting Yang's Blog
theme: ["PaperMod"]
outputs:
  home:
    - HTML
    - JSON # necessary for search
sectionPagesMenu: main
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - $$
            - $$
          inline:
          - - $
            - $
        enable: true
