dateFormat: "2006-01-02"
editPost:
  URL: "https://github.com/233yeee/233yeee.github.io/tree/main/content"
  Text: "Suggest Changes" # edit text
  appendFilePath: true # to append file path to Edit link
homeInfoParams:
  Title: 👋 Welcome to my blog
  Content: Thanks [Lil'Log](https://lilianweng.github.io/) which provide a good example of writing blogs.
socialIcons:
  - name: Github
    url: "https://github.com/yangyanting233"
  - name: Github
    url: "https://github.com/233yeee"
  - name: googlescholar
    url: "https://scholar.google.com/citations?hl=en&user=rbRk4Z4AAAAJ"
ShowReadingTime: true
ShowCodeCopyButtons: true
showtoc: true
ShowBreadCrumbs: true
